name: nyc_airbnb_dev
channels:
  - conda-forge
  - defaults
dependencies:
  - mlflow=2.5.0
  - ipython=7.21.0
  - notebook
  - jupyterlab
  - cookiecutter
  - hydra-core=1.0.6
  - matplotlib
  - pandas
  - git
  - pip
  - numpy=1.23.5
  - pip:
      - wandb==0.15.8
